package com.alvaroquintana.domain

data class Dog(
    var icon: String = "",
    var name: String = "",
    var origin: String = "",
    var breedGroup: String = "",
    var temperament: String = "",
    var description: String = "",
    var sizeCategory: String = "",
    var minWeightKg: Double = 0.0,
    var maxWeightKg: Double = 0.0,
    var minHeightCm: Double = 0.0,
    var maxHeightCm: Double = 0.0,
    var lifeSpanMin: Int = 0,
    var lifeSpanMax: Int = 0,
    var coatType: String = "",
    var colors: String = "",
    var exerciseNeeds: Int = 0,
    var groomingNeeds: Int = 0,
    var goodWithChildren: Int = 0,
    var goodWithOtherDogs: Int = 0,
    var trainability: Int = 0,
    var barkingLevel: Int = 0,
    var funFact: String = "",
    var images: String = "",
    var dataVersion: Int = 0,
    var nutrition: String = "",
    var hygiene: String = "",
    var lossHair: String = "",
    var commonDiseases: String = "",
    var otherNames: String = "",
    var fciGroup: Int = 0,
    var fciSection: Int = 0,
    var fciSectionType: String = "",
)
